import re, zlib, hashlib, sys

src = open(r"B:\Research\Git Projects Dsh\Deleted_files\refs\zlib_hash_tests.h", "r", encoding="ascii").read()

# --- long_string ---
m = re.search(r"static const uint8_t long_string\[5552\] = \{(.*?)\};", src, re.S)
chars = re.findall(r"'(\\.|[^'])'", m.group(1))
def unq(c):
    if c == "\\n": return 0x0a
    if c == "\\t": return 0x09
    if c == "\\\\" : return 0x5c
    if c == "\\'": return 0x27
    if c == '\\"': return 0x22
    if c == "\\r": return 0x0d
    if c == "\\b": return 0x08
    if c == "\\f": return 0x0c
    if c.startswith("\\x"): return int(c[2:], 16)
    if c.startswith("\\0"): return 0
    return ord(c)
long_bytes = bytes(unq(c) for c in chars)
assert len(long_bytes) == 5552, len(long_bytes)
assert zlib.adler32(long_bytes, 1) & 0xffffffff == 0x8b81718f, hex(zlib.adler32(long_bytes,1))
assert zlib.crc32(long_bytes) & 0xffffffff == 0x426fa73b
assert zlib.adler32(long_bytes, 0x7712aa45) & 0xffffffff == 0x7dc51be2

# --- vectors ---
m = re.search(r"static const hash_test hash_tests\[\] = \{(.*?)\n\};", src, re.S)
body = m.group(1)
vec_re = re.compile(
    r"\{\s*(\d+(?:\+\d+)*)\s*,\s*(?:\((?:const )?uint8_t\s*\*\)\s*)?"
    r"((?:\"(?:[^\"\\]|\\.)*\"\s*)+|long_string|big_test)\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*\}",
    re.S)
vecs = []
for mm in vec_re.finditer(body):
    ln = eval(mm.group(1))
    buf = mm.group(2)
    ia, ea, ic, ec = (int(mm.group(i), 16) for i in (3, 4, 5, 6))
    if buf.strip() == "long_string":
        kind = "Long"
        data = long_bytes
    elif buf.strip() == "big_test":
        kind = "Big"
        data = bytes(i % 256 for i in range(ln))
    else:
        parts = re.findall(r"\"((?:[^\"\\]|\\.)*)\"", buf)
        raw = b"".join(p.encode("ascii").decode("unicode_escape").encode("latin1") for p in parts)
        kind = "Text"
        # The len-1 vector uses an empty C string; the C test reads `len`
        # bytes from the (zero-padded) static buffer, i.e. one NUL byte.
        if len(raw) < ln:
            raw = raw.ljust(ln, b"\x00")
        data = raw
    assert len(data) == ln, (ln, len(data), data[:40])
    # verify with CPython
    got_a = zlib.adler32(data, ia) & 0xffffffff
    got_c = zlib.crc32(data, ic) & 0xffffffff
    assert got_a == ea, (ln, hex(ia), hex(got_a), hex(ea))
    assert got_c == ec, (ln, hex(ic), hex(got_c), hex(ec))
    vecs.append((ln, kind, data, ia, ea, ic, ec))

print("vectors:", len(vecs))
assert len(vecs) == 162, len(vecs)

# emit Rust data file
out = []
out.append("// AUTO-GENERATED by tools/gen_kat_data.py from Deleted_files/refs/zlib_hash_tests.h.")
out.append("// Do not edit by hand; re-run the generator if the source changes.")
out.append("//!")
out.append("//! Provenance: the `hash_tests[]` table (162 vectors) and `long_string[5552]`")
out.append("//! from zlib's test sources, extracted verbatim. Every vector was verified")
out.append("//! against CPython's `zlib.adler32` / `zlib.crc32` at generation time.")
out.append("")
out.append("pub const LONG_STRING: &[u8] = &[" + "")
line = []
for i, b in enumerate(long_bytes):
    line.append(format(b, "#04x"))
    if len(line) == 24:
        out.append("    " + ", ".join(line) + ",",)
        line = []
if line:
    out.append("    " + ", ".join(line) + ",")
out.append("];")
out.append("")
out.append("/// One hash KAT vector: (len, buf, initial_adler, expect_adler, initial_crc, expect_crc).")
out.append("/// `buf` is Empty (0 bytes), Nul (one 0x00 byte), Text, Long (LONG_STRING), or Big (i % 256).")
out.append("pub enum KatBuf { Empty, Nul, Text(&'static [u8]), Long, Big }")
out.append("")
out.append("pub struct Kat { pub len: u32, pub buf: KatBuf, pub init_adler: u32, pub exp_adler: u32, pub init_crc: u32, pub exp_crc: u32 }")
out.append("")
out.append("pub const HASH_KATS: &[Kat] = &[" + "")
for (ln, kind, data, ia, ea, ic, ec) in vecs:
    if kind == "Empty":
        b = "KatBuf::Empty"
    elif kind == "Nul":
        b = "KatBuf::Nul"
    elif kind == "Long":
        b = "KatBuf::Long"
    elif kind == "Big":
        b = "KatBuf::Big"
    else:
        b = "KatBuf::Nul" if (len(data) == 1 and data == b"\x00") else "KatBuf::Text(&[" + ", ".join(format(x, "#04x") for x in data) + "])"
    out.append(f"    Kat {{ len: {ln}, buf: {b}, init_adler: 0x{ia:08x}, exp_adler: 0x{ea:08x}, init_crc: 0x{ic:08x}, exp_crc: 0x{ec:08x} }},")
out.append("];")

text = "\n".join(out) + "\n"
open(r"B:\Research\Git Projects Dsh\Bitfold\src\kat_data.rs", "w", encoding="ascii").write(text)
print("wrote kat_data.rs, sha256:", hashlib.sha256(text.encode()).hexdigest()[:16])
print("first vector:", vecs[0][:2], vecs[0][2][:16])
print("last vector:", vecs[-1][:2])
print("long_string sha256:", hashlib.sha256(long_bytes).hexdigest()[:16])
print("adler(empty,0x1):", hex(zlib.adler32(b"", 1)), " crc(1x00,0):", hex(zlib.crc32(b"\x00")))
print("adler(empty,0xffffffff):", hex(zlib.adler32(b"", 0xffffffff) & 0xffffffff), " crc(empty,0xffffffff):", hex(zlib.crc32(b"", 0xffffffff) & 0xffffffff))
